sudo: false
language: rust

matrix:
  include:
    - rust: 1.36.0
    - rust: stable
    - rust: beta
    - rust: nightly
      name: Stable compiletest
    - rust: nightly
      name: Unstable compiletest
      env: FEATURES="unstable"
    - rust: nightly
      name: Minimal versions
      before_script: cargo update -Z minimal-versions
      script: cargo check
    - rust: 1.31.0
      script: cargo check

script:
  - cargo build --features "${FEATURES:-}"
  - cargo test --features "${FEATURES:-}"
