sudo: false
language: rust

matrix:
  include:
    - rust: 1.30.0
    - rust: stable
    - rust: beta
    - rust: nightly
      name: Stable compiletest
      env: TEST_FEATURES="compiletest"
    - rust: nightly
      name: Unstable compiletest
      env: FEATURES="unstable" TEST_FEATURES="compiletest unstable"

script:
  - cargo build --features "${FEATURES:-}"
  - cargo clean
  - cargo test --features "${FEATURES:-}"
  - cargo clean
  - cargo test --features "${TEST_FEATURES:-}" --manifest-path tests/Cargo.toml
